// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf_rQiyLEIOm1Y2FoePTCO8VnWbfPfWRI',
    appId: '1:991810776429:web:8ab6160152c84a30f9fe64',
    messagingSenderId: '991810776429',
    projectId: 'shopee-app-621eb',
    authDomain: 'shopee-app-621eb.firebaseapp.com',
    storageBucket: 'shopee-app-621eb.appspot.com',
    measurementId: 'G-XGVZRXN2M7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzMmrnjSUV87VG84i8cPsFrw_Ni2vfuqE',
    appId: '1:991810776429:android:45527cbdb773a10cf9fe64',
    messagingSenderId: '991810776429',
    projectId: 'shopee-app-621eb',
    storageBucket: 'shopee-app-621eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAec3DtRuWMF-kFuctTDt8TfS-iVkRSbG8',
    appId: '1:991810776429:ios:3147370dfc834262f9fe64',
    messagingSenderId: '991810776429',
    projectId: 'shopee-app-621eb',
    storageBucket: 'shopee-app-621eb.appspot.com',
    iosBundleId: 'com.example.shopee4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAec3DtRuWMF-kFuctTDt8TfS-iVkRSbG8',
    appId: '1:991810776429:ios:3147370dfc834262f9fe64',
    messagingSenderId: '991810776429',
    projectId: 'shopee-app-621eb',
    storageBucket: 'shopee-app-621eb.appspot.com',
    iosBundleId: 'com.example.shopee4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCf_rQiyLEIOm1Y2FoePTCO8VnWbfPfWRI',
    appId: '1:991810776429:web:f547febef70e76c3f9fe64',
    messagingSenderId: '991810776429',
    projectId: 'shopee-app-621eb',
    authDomain: 'shopee-app-621eb.firebaseapp.com',
    storageBucket: 'shopee-app-621eb.appspot.com',
    measurementId: 'G-HYKE6VG18X',
  );
}
